import type { Metadata } from "next";
import "./globals.css";
import { firaCode } from "./fonts";

export const metadata: Metadata = {
  title: "Lokendra Nath",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${firaCode.className} antialiased`}
        suppressHydrationWarning={true}
      >
        {children}
      </body>
    </html>
  );
}
